"""drop persist from user_api_keys

Revision ID: 04557a304a38
Revises: b5d7a9c2e1f3
Create Date: 2026-05-09 01:10:50.475343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04557a304a38"
down_revision: Union[str, None] = "b5d7a9c2e1f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_usage_user_id"), table_name="agent_usage")
    op.drop_index(op.f("uq_categories_user_type_normalized_name"), table_name="categories")
    op.drop_index(op.f("uq_subcategories_user_category_normalized_name"), table_name="subcategories")
    op.drop_constraint(op.f("uq_user_api_keys_user_id"), "user_api_keys", type_="unique")
    op.drop_index(op.f("ix_user_api_keys_user_id"), table_name="user_api_keys")
    op.create_index(op.f("ix_user_api_keys_user_id"), "user_api_keys", ["user_id"], unique=True)
    op.drop_column("user_api_keys", "persist")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_api_keys",
        sa.Column("persist", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_user_api_keys_user_id"), table_name="user_api_keys")
    op.create_index(op.f("ix_user_api_keys_user_id"), "user_api_keys", ["user_id"], unique=False)
    op.create_unique_constraint(
        op.f("uq_user_api_keys_user_id"), "user_api_keys", ["user_id"], postgresql_nulls_not_distinct=False
    )
    op.create_index(
        op.f("uq_subcategories_user_category_normalized_name"),
        "subcategories",
        ["user_id", "category_id", sa.literal_column("lower(btrim(name::text))")],
        unique=True,
    )
    op.create_index(
        op.f("uq_categories_user_type_normalized_name"),
        "categories",
        ["user_id", "type", sa.literal_column("lower(btrim(name::text))")],
        unique=True,
    )
    op.create_index(op.f("ix_agent_usage_user_id"), "agent_usage", ["user_id"], unique=False)
    # ### end Alembic commands ###
