"""replace category string with category_id fk in transactions

Revision ID: 45022d06d57c
Revises: c1a9e7f4b2d8
Create Date: 2026-03-31 23:17:36.689394

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "45022d06d57c"
down_revision: Union[str, None] = "c1a9e7f4b2d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("category_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False)
    op.create_foreign_key(None, "transactions", "categories", ["category_id"], ["id"], ondelete="SET NULL")
    op.drop_column("transactions", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transactions", sa.Column("category", sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, "transactions", type_="foreignkey")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_column("transactions", "category_id")
    # ### end Alembic commands ###
