"""add_google_id_to_users

Revision ID: ab0a8eded134
Revises: f08f4f06a9aa
Create Date: 2026-03-05 01:22:57.182268

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab0a8eded134"
down_revision: Union[str, None] = "f08f4f06a9aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.String(length=255), nullable=False))
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
